### ISSUE TITLE
How do I access dropzone from within the closures?

### ISSUE THREAD

**Issue by kaned** [atsjj/ember-dropzone#1]
This is a great wrapper for Dropzone, thanks for creating it.

I am trying to access the dropzone object from the 'drop' event, but my 'this' is being overridden in Ember to point to the outer Ember class (shows up in the Chrome debugger as '_this'), instead of the Dropzone one. So when 'this.removeAllFiles(true)' is called I get an error because 'removeAllFiles' is not a function of the Ember class.

How can I access dropzone from with the closure?

```
insertDropzone: function() {
  this.$().dropzone({
    maxFiles: 1,
    drop: (event) => {
       this.removeAllFiles(true);
    }
  });
}.on('didInsertElement')
```

I am pretty new to ember and tried 'var self = this;', which works with promises, and 'this.$().dropzone', which was a bit of a long shot, but neither worked.

**Comment by atsjj** [comment]
Try this out:

```
insertDropzone: function() {
  var self = this;
  this.$().dropzone({
    maxFiles: 1,
    drop: function(event) {
       this.removeAllFiles(true);
       self.someOtherAction();
    }
  });
}.on('didInsertElement')
```

**Comment by kaned** [comment]
@atsjj thanks for the response. However, this approach is exactly what is not working for me. 

I am running Ember 1.11.3 and Ember-CLI 0.2.7, and with both 'this.removeAllFiles(true)' and 'self.removeAllFiles(true)' I get the same error that it is not a function. Even though from the Chrome console I can call these fine. It seems somewhere in the bowels of Ember the 'this' is being converted to '_this'. So when I look in the debugger I see:

```
insertDropzone: (function () {
  var _this = this;      <- this was added automagically
  var self = this;
  this.$().dropzone({
       maxFiles: 1,
       drop: (event) => {
            _this.removeAllFiles(true);   <- TypeError _this.removeAllFiles is not a function
            self.removeAllFiles(true);     <- TypeError self.removeAllFiles is not a function
       }
   });
}.on('didInsertElement')
```

Now, I am not sure if the conversion to '_this' is really the issue, could be a red herring. Either way, I can find a way to reference the dropzone object from within the 'drop' closure event.

Does this work for you? Are you on different version of ember or ember-cli?

**Comment by atsjj** [comment]
So, the important part here is if the function assigned to the `drop` property is being called by the Dropzone library with `this` assigned to it's context, then we have to get rid of the fat arrows so we don't change the scope of `this` to the Ember Component.

The code I posted above does that. If the assigned function isn't being passed the dropzone context as `this`, then I'm not quite sure what the fix is. I'd have to hack on the dropzone lib, because I'm unfamiliar with it's API.

Does this help?

**Comment by kaned** [comment]
@atsjj Ah!, it was the fat arrows. I completely glossed over those with your first response. My apologies for missing that. Removing them solved my problem.

Thanks for the help!

**Comment by atsjj** [comment]
@kaned np, glad to help!
